### ISSUE TITLE
When hide receipts is enabled, the other person wont receive the delivery notification

### ISSUE THREAD

**Issue by jsalatiel** [suraj0208/WhatsappExtensions#10]
I think i found another bug, i have enable "hide read receipts" and have 'delivery notification' enabled, but apparently, in this setup the people wont get the delivery notification ( second tick ). It will get  just one tick forever!

**Comment by suraj0208** [comment]
Nothing can be done about it. Delivery reports are sent when you clear whatsapp from recent apps. Thats how it works. Its their implementation. I'm closing this issue.
