### ISSUE TITLE
Select all contacts

### ISSUE THREAD

**Issue by manufuentescr** [suraj0208/WhatsappExtensions#16]
There is the option to select all the contacts to forward a message ?

![forward](https://cloud.githubusercontent.com/assets/2752593/20894309/7f8f7ac6-bada-11e6-9d03-6ccff4ef0d28.png)

**Comment by suraj0208** [comment]
Sorry I didnt get you ? do you want a feature to select all contacts while forwarding ?

**Comment by manufuentescr** [comment]
Yes. it's possible ?

**Comment by suraj0208** [comment]
I have to see how the code is implemented. Cannot say anything for sure

**Comment by manufuentescr** [comment]
I understand, thanks that would be a good implementation

**Comment by suraj0208** [comment]
Please make feature requests on XDA thread. This section is for issues. Closing this topic.
