### ISSUE TITLE
Last response cloak unconsistent

### ISSUE THREAD

**Issue by jrotaetxe** [suraj0208/WhatsappExtensions#33]
When I protect a contact, and depending the contact, his/her last responses (or my last response) is not cloaked in the chat list. So far happens only with some international contacts, and does not depend on the country (I have failing and running contacts with the same international prefix).
Could be "exotic" characters in his phone numbers?.
seems is not related on how I has stored the contact, but the contact info that comes with the message and then is processed by whatsapp. Deleted the contact in my Gmail and re-defined. No successs
Happens in different phones, with different Android versions
Thank you for your nice work....

**Comment by suraj0208** [comment]
for some contacts the the contact jid format was different in tag. handled it explicitly

https://github.com/suraj0208/WhatsappExtensions/commit/991a0e2f2aea6fe722315f07af413e6e110af3e1#diff-c8cc75e305fd1f5ab7680105a817db4b
