### ISSUE TITLE
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported Android N

### ISSUE THREAD

**Issue by Jasi2169** [suraj0208/WhatsappExtensions#35]
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

on android Nougat but i see the latest version is released in september and you made changes 7 days back to make it private.

are you going to release next version for nougat compatibility

seems you need to make your shared_prefs worldredable

also xposed can not read prefs on FBE enabled devices now

**Comment by Jasi2169** [comment]
added unofficial build for nougat

https://forum.xda-developers.com/showpost.php?p=74205487&postcount=1224

**Comment by suraj0208** [comment]
I've worked on making it world readable. Haven't released it yet. So is there any work around for FBE enabled devices? What was your approach for making it world readable?

**Comment by Jasi2169** [comment]
Hi,i used File APi to setreadable(true,false) rrr to all now this works fine, so making worldreadable with fle api to prefs is possible :)

**Comment by Jasi2169** [comment]
you could use root to chmod as well

**Comment by suraj0208** [comment]
Yeah i used root. Setting it to rw for all.

**Comment by suraj0208** [comment]
For some reason I am not able to get it to work. I've pushed the changes in master. Can you please see whats wrong. The world readable related code is in Utils.java and I'm calling the function in onpause. 
Please see I dont have a phone with android N

**Comment by Jasi2169** [comment]
added pull request
