### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by r4nm4** [suraj0208/WhatsappExtensions#38]
[deleted]

**Comment by Mhitra** [comment]
Thank you @badjester for your fork and your "improvements for hiding chats" code.
Definitely is exactly what I'm looking for!
Thanks

**Comment by suraj0208** [comment]
@badjester whatever changes you've done in LockPreferenceService to make it work for nougat, Are they working for you?
I did same and many users complained that they cannot archive chats. I had problems too. where it couldnt set the read permissions to shared prefs file. 
I did a chmod from the same service and it appears to be working.

**Comment by badjester** [comment]
It isn't working if I hide chats and then restart WhatsApp, as it should be.
But as far I can see it is working if I hide chats, switch to WhatsApp Extensions settings and send it to background (to get a call of onPause). After this I restart WhatsApp and it works.
Looks like only the activity can change the permissions of the file?

**Comment by suraj0208** [comment]
Yeah what I think is when LockPreferenceService is started from whatsapp it doesnt allow permissions to be changed. I didnt check the logcat if exception was thrown ( do check it for learning purpose and update me :D ) . So decided to do chmod from there.

**Comment by badjester** [comment]
Have you seen this? Maybe you App has to request the write permissions in addition to the manifest entry so this is working?

https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android

**Comment by minazvakil** [comment]
Any update on this Surajkumar. Have you been able to solve this.

**Comment by minazvakil** [comment]
@badjester -can u suggest me how to activate this ?
