### ISSUE TITLE
Whatsapp Extensions: 5.8.1 doesn't show any effect on Nougat

### ISSUE THREAD

**Issue by winstonma** [suraj0208/WhatsappExtensions#39]
Hi

I installed WhatsappExtensions and granted root access (via Magisk). I successfully opened WhatsappExtensions and make some config, however I don't see any changes on WhatsApp.

Thanks

Here are the details:
WhatsApp: 2.17.387
Android: 7.1.2
Whatsapp Extensions: 5.8.1 (From Beta Channel)

**Comment by rehannali** [comment]
Same issue with me.

**Comment by suraj0208** [comment]
Working on that.
Thanks

**Comment by suraj0208** [comment]
Fixed the issue in latest commit on master. Closing the issue.
