### ISSUE TITLE
[FEATURE REQUEST] Avoid deleting of messages

### ISSUE THREAD

**Issue by FrancYescO** [suraj0208/WhatsappExtensions#40]
As today whatsapp added the possibility to revoke sent messages

If some contact revoke a message sent to you, just avoid that the message will be deleted on your client

**Comment by Lanchon** [comment]
each deleted message is replaced by text stating the deletion. ideally, the delete request should not be honored but it should be logged anyway. inserting a message before the one to be deleted would do the trick:
- `Deletion requested[ at <timestamp>][ for[ this message]]:`
- `Revoked[ at <timestamp>]:`

**Comment by suraj0208** [comment]
Its a nice feature actually. I have to see what method is called when the delete request is received and I can call param.setResult to skip that method.
Thanks
