### ISSUE TITLE
issue: Permanently hide messages - Empty list

### ISSUE THREAD

**Issue by Mhitra** [suraj0208/WhatsappExtensions#47]
Hi @suraj0208 ,
I'm sorry to bother you, but I'm trying to use the option "Permanently hide messages".

When I click on the cog icon, I can see a white page with "list in empty" toast.
If I click on + fab, I have another white page with on the top "Search for Contact".
That's all, nothing happen. I don't know how to insert some contact inside this list.
I have checked my permission and the app is allowed to read from my phone contact list.

Any issue by my side?

Thank you so much.
Cheers

**Comment by suraj0208** [comment]
have you installed sqlite?
check XDA thread FAQ

**Comment by Mhitra** [comment]
EPIC FAIL, my bad, truly sorry

**Comment by Mhitra** [comment]
I'm sorry @suraj0208 I have installed SQLite binary... but same issue.
And I don't see any XDA thread FAQ in your topic about this issue and SQLite :(
Can you link? Please
