### ISSUE TITLE
Hide conversation has no effect now

### ISSUE THREAD

**Issue by bilogic** [suraj0208/WhatsappExtensions#51]
Hi, 

After the recent WhatsApp update, the hide conversation functionality has no effect, i.e. it does not hide the conversation anymore. Able to fix? 

Thank you.

**Comment by suraj0208** [comment]
I've fixed. Not working on this module actively. I'll update once done.

**Comment by bilogic** [comment]
Hi,

Thanks. But I don't see any commits or updates on Xposed?

**Comment by suraj0208** [comment]
I'll push the changes. Currently I'm way too busy with office work. I hardcoded somethings to get working so didnt push the code.

**Comment by bilogic** [comment]
Ok, understand. I will wait. Thank you.

**Comment by bilogic** [comment]
Hi, would you mind sharing the changes you made here? I can help clean up the hardcoded parts and make a pull request. Thank you.

**Comment by suraj0208** [comment]
sorry I'll push today

**Comment by bilogic** [comment]
Hi,

I think there was new WhatsApp update these few days. Hide stopped working again. Could you have a look? Thank you.

**Comment by bilogic** [comment]
Hi,

I just want to highlight that the following released versions of WhatsappExtensions have issues with the latest WhatsApp 2.19.17:

- 6.1 - WhatsApp crashes
- 6.2 - Cannot install, error is "App not installed"
- 6.3 - Cannot install, error is "App not installed"
- 6.31 - WhatsApp crashes

Only the earlier unreleased WhatsappExtensions 6.13 is works.
Thank you.

**Comment by suraj0208** [comment]
which android version are you using?

**Comment by suraj0208** [comment]
also if possible send logcat. I just tried and its working at my end

**Comment by bilogic** [comment]
I'm on Marshmellow. Logcat, let me try.

**Comment by bilogic** [comment]
Hi,

The logcat for WhatsApp 2.19.98 and WhatsAppExtensions 6.31.
Thank you.

[logcat_04-12-2019_21-59-10.txt](https://github.com/suraj0208/WhatsappExtensions/files/3073589/logcat_04-12-2019_21-59-10.txt)

**Comment by bilogic** [comment]
Hi,

Looking at the logs, why does WhatsApp keep trying to create the table ```new_sticker_packs```, which already exists? This happens only when ```WhatsappExtensions``` is in use.

**Comment by bilogic** [comment]
@suraj0208 are you seeing this or should I open a new ticket? Thank you.
