### ISSUE TITLE
[Feature Request] Add option to disable deletion of messages.

### ISSUE THREAD

**Issue by gergesh** [suraj0208/WhatsappExtensions#52]
What I'm looking for: when someone chooses to delete a message for everyone, it will not get deleted from the device. Would be even better if I was notified the message was supposed to be deleted in some way.
For implementation, perhaps @Krowne could share some details?

**Comment by Krowne** [comment]
This feature was added several versions ago in my module.

**Comment by Krowne** [comment]
@gergesh This feature was added several versions ago in my module.

**Comment by gergesh** [comment]
@Krowne I am aware, that's why I tagged you. I prefer WAEx because the theming and misc. capabilities of your module make it much heavier and more difficult to manage than this module.
Is the source for your module available anywhere? I couldn't find it.

**Comment by Krowne** [comment]
No, I'm sorry, the source code is closed. I'm working on a new module, which will download only the information on which you want to work, therefore, it will be much lighter. Unfortunately, I can not give you a release date, because the project is in pre-development.

**Comment by gergesh** [comment]
@Krowne great to know, if you're ever looking for beta testers I'd love to help.

**Comment by suraj0208** [comment]
added in
https://github.com/suraj0208/WhatsappExtensions/commit/304caed054a93df05c187469f6385b3df9a88bd2
