### ISSUE TITLE
Contact list empty.

### ISSUE THREAD

**Issue by fahadakhan96** [suraj0208/WhatsappExtensions#57]
When trying to add a contact to whitelist/blacklist, no contacts show up. Screenshot below.

![image](https://user-images.githubusercontent.com/3263435/42725567-1bfb6496-879f-11e8-902b-f9ebf874c9c9.png)

**Comment by hollowsxd** [comment]
Have you give the app contacts permission?

**Comment by fahadakhan96** [comment]
It didn't ask for permission. There was only Phone and Storage permission in the permissions list both of which I tried allowing to no success. 

P.S. I've since uninstalled the app. Feel free to close this issue if you wish.

**Comment by suraj0208** [comment]
added a toast to read what caused the failure
https://github.com/suraj0208/WhatsappExtensions/commit/991a0e2f2aea6fe722315f07af413e6e110af3e1
